# Generated by Django 4.1.3 on 2023-04-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_inplay_odds',
            name='time',
            field=models.DateTimeField(blank=True, default='Mon Apr 17 02:09:19 2023'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateTimeField(blank=True, default='Mon Apr 17 02:09:19 2023'),
        ),
        migrations.AlterField(
            model_name='vip_games',
            name='time',
            field=models.DateTimeField(blank=True, default='Mon Apr 17 02:09:19 2023', null=True),
        ),
    ]
