# Generated by Django 4.1.3 on 2023-04-17 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_vip_odds_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_betoftheday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='vip_games',
            name='Prediction',
            field=models.CharField(blank=True, max_length=300, verbose_name='prediction'),
        ),
    ]
