# Generated by Django 4.1.3 on 2023-04-17 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_game_is_betoftheday_alter_game_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vip_odds',
            name='category',
        ),
        migrations.AddField(
            model_name='vip_games',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odds_categories', to='backend.categories'),
        ),
        migrations.AlterField(
            model_name='vip_odds',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='vip_games', to='backend.vip_games'),
        ),
    ]
