# Generated by Django 4.1.3 on 2023-04-17 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_vip_odds_category_vip_games_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vip_games',
            name='category',
        ),
        migrations.AddField(
            model_name='vip_odds',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odds_categories', to='backend.categories'),
        ),
    ]
