# Generated by Django 4.1.3 on 2023-04-17 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_vip_games_category_vip_odds_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip_games',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vip_categories', to='backend.categories'),
        ),
    ]
