# Generated by Django 4.1.8 on 2023-04-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_vip_games_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_inplay_odds',
            name='time',
            field=models.DateTimeField(blank=True, default='2023-04-30 21:07'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateTimeField(blank=True, default='2023-04-30 21:07', null=True),
        ),
    ]
