# Generated by Django 4.1.8 on 2023-04-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_free_inplay_odds_time_alter_game_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_inplay_odds',
            name='time',
            field=models.DateTimeField(blank=True, default='2023-04-30 21:11'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateTimeField(blank=True, default='2023-04-30 21:11', null=True),
        ),
        migrations.AlterField(
            model_name='vip_games',
            name='time',
            field=models.DateTimeField(blank=True, default='2023-04-30 21:11', null=True),
        ),
        migrations.AlterField(
            model_name='vip_odds',
            name='date',
            field=models.DateField(blank=True, default='2023-04-30 21:11', null=True),
        ),
    ]
