# Generated by Django 4.1.8 on 2023-05-01 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_free_inplay_odds_time_alter_game_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_inplay_odds',
            name='time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vip_games',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vip_odds',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 1, 21, 20, 7, 354474), null=True),
        ),
    ]
