# Generated by Django 4.1.8 on 2023-05-02 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_free_inplay_odds_time_alter_game_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip_odds',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 2, 7, 30, 58, 808111), null=True),
        ),
    ]
